### ISSUE TITLE
Running linting

### ISSUE THREAD

**Issue by rangeetpan** [IBM/codellm-devkit#20]

**Comment by rahlk** [comment]
Sample pre commit linting in a file called `.pre-commit-config.yaml`

```
repos:
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [--remove-all-unused-imports, --remove-unused-variables, --in-place, --recursive]
  
  - repo: https://github.com/psf/black
    rev: 24.4.0 
    hooks:
      - id: black
        args: [--line-length=180]
```

**Comment by timrbula** [comment]
I'd suggest trying [ruff](https://docs.astral.sh/ruff/) for linting, formatting and import sorting to consolidate to one tool and for performance. 

e.g.

```
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.1
    hooks:
      # Run the Ruff linter.
      - id: ruff
        args: [ --fix ]
      # Run the Ruff formatter.
      - id: ruff-format
```
